import type { Metadata } from "next";
import { Jura } from "next/font/google";
import "./globals.css";

const jura = Jura({
  variable: "--font-jura",
  subsets: ["latin"],
  weight: ["400", "700"], // Example: Include regular and bold weights
});

export const metadata: Metadata = {
  title: "Recommendations by Coonfituuree",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${jura.variable} antialiased text-2xl`}>
        {children}
      </body>
    </html>
  );
}
